/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSurveysRouteImport } from './routes/_app.surveys'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssignedRouteImport } from './routes/_app.assigned'
import { Route as AppSurveysIdRouteImport } from './routes/_app.surveys.$id'
import { Route as AppAssignedIdRouteImport } from './routes/_app.assigned.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminGroupsRouteImport } from './routes/_app.admin.groups'
import { Route as AppAdminActivityRouteImport } from './routes/_app.admin.activity'
import { Route as AppSurveysIdProgressRouteImport } from './routes/_app.surveys.$id.progress'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignedRoute = AppAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIdRoute = AppSurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppAssignedIdRoute = AppAssignedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssignedRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGroupsRoute = AppAdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIdProgressRoute = AppSurveysIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppSurveysIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assigned': typeof AppAssignedRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/surveys': typeof AppSurveysRouteWithChildren
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/groups': typeof AppAdminGroupsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/assigned/$id': typeof AppAssignedIdRoute
  '/surveys/$id': typeof AppSurveysIdRouteWithChildren
  '/surveys/$id/progress': typeof AppSurveysIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assigned': typeof AppAssignedRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/surveys': typeof AppSurveysRouteWithChildren
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/groups': typeof AppAdminGroupsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/assigned/$id': typeof AppAssignedIdRoute
  '/surveys/$id': typeof AppSurveysIdRouteWithChildren
  '/surveys/$id/progress': typeof AppSurveysIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/assigned': typeof AppAssignedRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/surveys': typeof AppSurveysRouteWithChildren
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/groups': typeof AppAdminGroupsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/assigned/$id': typeof AppAssignedIdRoute
  '/_app/surveys/$id': typeof AppSurveysIdRouteWithChildren
  '/_app/surveys/$id/progress': typeof AppSurveysIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assigned'
    | '/dashboard'
    | '/surveys'
    | '/admin/activity'
    | '/admin/groups'
    | '/admin/users'
    | '/assigned/$id'
    | '/surveys/$id'
    | '/surveys/$id/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assigned'
    | '/dashboard'
    | '/surveys'
    | '/admin/activity'
    | '/admin/groups'
    | '/admin/users'
    | '/assigned/$id'
    | '/surveys/$id'
    | '/surveys/$id/progress'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/assigned'
    | '/_app/dashboard'
    | '/_app/surveys'
    | '/_app/admin/activity'
    | '/_app/admin/groups'
    | '/_app/admin/users'
    | '/_app/assigned/$id'
    | '/_app/surveys/$id'
    | '/_app/surveys/$id/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/surveys': {
      id: '/_app/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assigned': {
      id: '/_app/assigned'
      path: '/assigned'
      fullPath: '/assigned'
      preLoaderRoute: typeof AppAssignedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$id': {
      id: '/_app/surveys/$id'
      path: '/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof AppSurveysIdRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/assigned/$id': {
      id: '/_app/assigned/$id'
      path: '/$id'
      fullPath: '/assigned/$id'
      preLoaderRoute: typeof AppAssignedIdRouteImport
      parentRoute: typeof AppAssignedRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/groups': {
      id: '/_app/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$id/progress': {
      id: '/_app/surveys/$id/progress'
      path: '/progress'
      fullPath: '/surveys/$id/progress'
      preLoaderRoute: typeof AppSurveysIdProgressRouteImport
      parentRoute: typeof AppSurveysIdRoute
    }
  }
}

interface AppAssignedRouteChildren {
  AppAssignedIdRoute: typeof AppAssignedIdRoute
}

const AppAssignedRouteChildren: AppAssignedRouteChildren = {
  AppAssignedIdRoute: AppAssignedIdRoute,
}

const AppAssignedRouteWithChildren = AppAssignedRoute._addFileChildren(
  AppAssignedRouteChildren,
)

interface AppSurveysIdRouteChildren {
  AppSurveysIdProgressRoute: typeof AppSurveysIdProgressRoute
}

const AppSurveysIdRouteChildren: AppSurveysIdRouteChildren = {
  AppSurveysIdProgressRoute: AppSurveysIdProgressRoute,
}

const AppSurveysIdRouteWithChildren = AppSurveysIdRoute._addFileChildren(
  AppSurveysIdRouteChildren,
)

interface AppSurveysRouteChildren {
  AppSurveysIdRoute: typeof AppSurveysIdRouteWithChildren
}

const AppSurveysRouteChildren: AppSurveysRouteChildren = {
  AppSurveysIdRoute: AppSurveysIdRouteWithChildren,
}

const AppSurveysRouteWithChildren = AppSurveysRoute._addFileChildren(
  AppSurveysRouteChildren,
)

interface AppRouteChildren {
  AppAssignedRoute: typeof AppAssignedRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSurveysRoute: typeof AppSurveysRouteWithChildren
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminGroupsRoute: typeof AppAdminGroupsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignedRoute: AppAssignedRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSurveysRoute: AppSurveysRouteWithChildren,
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminGroupsRoute: AppAdminGroupsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
